#' Zoom in on a spectral range
#'
#' @description It's common to be interested in only a small portion of the FTIR
#'   range. In these cases, this function will zoom the spectral plot to the
#'   range provided.
#'
#'   Il est courant de s'intéresser uniquement à une petite partie de la plage
#'   FTIR. Dans ces cas, cette fonction zoomera sur le tracé spectral sur la
#'   plage fournie.
#'
#'
#' @param ftir_spectra_plot A plot generated by [plot_ftir()] or
#'   [plot_ftir_stacked()].
#'
#'   Un tracé généré par [plot_ftir()] ou [plot_ftir_stacked()].
#'
#' @param zoom_range A vector of length two, with the wavenumber range of
#'   interest. Order of provided limits is not important.
#'
#'   Un vecteur de longueur deux, avec la plage de nombres d'onde qui nous
#'   intéresse. L’ordre des limites fournies n’est pas important.
#'
#' @return a ggplot2 object, with x axis limits as those supplied by
#'   `zoom_range`.
#'
#'   un objet ggplot2, avec des limites d'axe x comme celles fournies par `zoom_range`.
#'
#' @export
#'
#' @examples
#' # Generate a plot
#' biodiesel_plot <- plot_ftir(biodiesel)
#'
#' # Zoom to a specified range of 1850 to 1650 cm^-1
#' zoom_in_on_range(biodiesel_plot, c(1650, 1850))
zoom_in_on_range <- function(ftir_spectra_plot, zoom_range = c(1000, 1900)) {
  if (!(inherits(ftir_spectra_plot, "ggplot"))) {
    cli::cli_abort("{.arg ftir_spectra_plot} must be a ggplot object. You provided a {.cls {class ftir_spectra_plot}}")
  }

  if (!(length(zoom_range) == 2)) {
    cli::cli_abort("{.arg zoom_range} must be a numeric vector of length two.")
  }
  if (!all(is.numeric(zoom_range))) {
    cli::cli_abort("{.arg zoom_range} must be numeric values")
  }

  if (any(zoom_range < 400) || any(zoom_range > 4000)) {
    cli::cli_abort("{.arg zoom_range} must be values between 400 and 4000 cm^-1.")
  }

  suppressMessages(p <- ftir_spectra_plot + ggplot2::scale_x_reverse(limits = c(max(zoom_range), min(zoom_range))))

  return(p)
}

