#' Zoom in on a spectral range
#'
#' @description It's common to be interested in only a small portion of the FTIR
#'   range. In these cases, this function will zoom the spectral plot to the
#'   range provided.
#'
#'   Il est courant de s'intéresser uniquement à une petite partie de la plage
#'   IRTF Dans ces cas, cette fonction zoomera sur le tracé spectral sur la
#'   plage fournie.
#'
#'
#' @param ftir_spectra_plot A plot generated by [plot_ftir()] or
#'   [plot_ftir_stacked()].
#'
#'   Un tracé généré par [plot_ftir()] ou [plot_ftir_stacked()].
#'
#' @param zoom_range A vector of length two, with the wavenumber range of
#'   interest. Order of provided limits is not important.
#'
#'   Un vecteur de longueur deux, avec la plage de nombres d'onde qui nous
#'   intéresse. L’ordre des limites fournies n’est pas important.
#'
#' @return the FTIR plot as a ggplot2 object, with x axis limits as those supplied by
#'   `zoom_range`.
#'
#'   le tracé IRTF en tant qu'objet ggplot2, avec des limites d'axe x comme celles fournies par `zoom_range`.
#'
#' @export
#'
#' @examples
#' # Generate a plot
#' biodiesel_plot <- plot_ftir(biodiesel)
#'
#' # Zoom to a specified range of 1850 to 1650 cm^-1
#' zoom_in_on_range(biodiesel_plot, c(1650, 1850))
zoom_in_on_range <- function(ftir_spectra_plot, zoom_range = c(1000, 1900)) {
  if (!ggplot2::is.ggplot(ftir_spectra_plot)) {
    cli::cli_abort("{.arg ftir_spectra_plot} must be a ggplot object. You provided {.obj_type_friendly {ftir_spectra_plot}}.")
  }

  if (!(length(zoom_range) == 2) | !all(is.numeric(zoom_range))) {
    cli::cli_abort("{.arg zoom_range} must be a numeric vector of length two.")
  }

  if (any(zoom_range < 400, zoom_range > 4000)) {
    cli::cli_abort("{.arg zoom_range} must be values between 400 and 4000 cm^-1.")
  }

  suppressMessages(p <- ftir_spectra_plot + ggplot2::scale_x_reverse(limits = c(max(zoom_range), min(zoom_range))))

  return(p)
}


#' Compression Transformation
#'
#' @description used in `compress_low_energy()`
#' utilisé en `compress_low_energy`()`
#'
#' @param intercept the wavenumber at which compression starts
#' le numéro d'onde auquel la compression commence
#' @param ratio the rate of compression (larger numbers are more compressed)
#' le taux de compression (des nombres plus grands sont plus compressés)
#'
#' @references From https://stackoverflow.com/a/43321639 & https://stackoverflow.com/a/78360580
#' @keywords internal
compress_trans <- function(intercept = 2000, ratio = 5) {
  # For FTIR, note that the plot has scale_x_reverse() always applied to it.
  # So, we're really talking about intercept as a -1*intercept

  intercept <- intercept * -1

  scales::trans_new("compress",
    transform = function(x) {
      ifelse(x > intercept, x, (x - intercept) / ratio + intercept)
    },
    inverse = function(x) {
      ifelse(x > intercept, x, ((x - intercept) * ratio) + intercept)
    }
  )
}


#' Add GGPlot Layer below others
#'
#' @description Inserts a layer *underneath* the existing layers on a ggplot
#'   object simply by calling `plot` - `layer` instead of the usual `plot` +
#'   `layer`.
#'
#'   Insère un calque *sous* les calques existants sur un objet ggplot
#'   simplement en appelant `plot` - `layer` au lieu de l'habituel `plot` +
#'   `layer`.
#'
#' @param plot The plot to which the layer should be added.
#'
#'   Le tracé auquel le calque doit être ajouté.
#'
#' @param layer The layer to add to the plot.
#'
#' La couche à ajouter au tracé.
#'
#' @return The ggplot2 `plot` object, with layer `layer` added underneath.
#'
#'   L'objet ggplot2 `plot`, avec le calque `layer` ajouté en dessous.
#' @export
#'
#' @keywords internal
#'
#' @references From https://stackoverflow.com/a/64011534
`-.gg` <- function(plot, layer) {
  if (is.null(layer) | missing(layer)) {
    cli::cli_abort(c("Cannot use {.code -.gg()} with a single argument, it must be followed by a {.arg layer}.",
                     i = "Did you accidentally put {.code -} on a new line?"))
  }
  if (!ggplot2::is.ggplot(plot)) {
    cli::cli_abort("You need to have a ggplot on the left side. You provided {.obj_type_friendly { plot }}.")
  }
  plot$layers <- c(layer, plot$layers)
  plot
}

#' Compress Low-Energy Region
#'
#' @description Compress the lower energy region of a FTIR plot (on the x axis) to
#'   leave more space for the higher-energy region. This is commonly done for
#'   wavenumbers higher than 2000 cm^-1 as the more complex spectra at higher
#'   energy (lower wavenumber) is harder to see clearly.
#'
#'   Compressez la région d'énergie inférieure d'un tracé d'IRTF (sur l'axe des x) pour
#'   laisser plus d'espace à la région d'énergie supérieure. Ceci est
#'   généralement effectué pour les nombres d'onde supérieurs à 2000 cm^-1, car
#'   les spectres plus complexes à une énergie plus élevée (nombre d'onde
#'   inférieur) sont plus difficiles à voir clairement.
#'
#' @param ftir_spectra_plot A plot generated by [plot_ftir()] or
#'   [plot_ftir_stacked()].
#'
#'   Un tracé généré par [plot_ftir()] ou [plot_ftir_stacked()].
#'
#' @param cutoff The wavenumber whereat those at lower energy will be
#'   compressed, but those above will be shown normally.
#'
#'   Le nombre d'onde auquel ceux à énergie au-desous seront compressés, mais
#'   ceux au-dessus seront affichés normalement.
#'
#' @param compression_ratio A numeric value indicating the ratio by which to
#'   squeeze the data
#'
#'   Une valeur numérique indiquant le rapport selon lequel compresser les
#'   données
#'
#' @return the FTIR plot as a ggplot2 object, with x axis compressed for some
#'   wavenumber range
#'
#'   le tracé FTIR en tant qu'objet ggplot2, avec l'axe x compressé pour une
#'   plage de nombres d'onde
#'
#' @export
#'
#' @examples
#' # Generate a plot
#' biodiesel_plot <- plot_ftir(biodiesel)
#'
#' # Compress below 2000 cm^-1 by a factor of 5
#' compress_low_energy(biodiesel_plot, cutoff = 2000, compression_ratio = 5)
compress_low_energy <- function(ftir_spectra_plot, cutoff = 2000, compression_ratio = 2) {
  if (!ggplot2::is.ggplot(ftir_spectra_plot)) {
    cli::cli_abort("{.arg ftir_spectra_plot} must be a ggplot object. You provided {.obj_type_friendly {ftir_spectra_plot}}.")
  }

  if (!is.numeric(cutoff)) {
    cli::cli_abort("{.arg cutoff} must be a numeric value. You provided {.obj_type_friendly {cutoff}}.")
  }

  if (cutoff < 400 || cutoff > 4000) {
    cli::cli_abort("{.arg cutoff} must be a value between 400 and 4000 cm^-1.")
  }

  if (!is.numeric(compression_ratio)) {
    cli::cli_abort("{.arg compression_ratio} must be a numeric value. You provided {.obj_type_friendly {compression_ratio}}.")
  }

  if (compression_ratio < 0.01 || compression_ratio > 100) {
    cli::cli_abort("{.arg compression_ratio} must be a value between 0.01 and 100.")
  }

  p <- ftir_spectra_plot +
    ggplot2::coord_trans(x = compress_trans(intercept = cutoff, ratio = compression_ratio))

  return(p)
}


#' Add a Marker at a Wavenumber
#'
#' @description Add a vertical line marker, at a given wavenumber, to an FTIR
#'   plot, and label at the top of the plot with a provided text (or default the
#'   wavenumber of the marker). This is useful for noting important wavenumbers.
#'
#'   This function can be called repeatedly. Note that older labels will be
#'   overwritten by newer labels.
#'
#'   Ajoutez un marqueur de ligne verticale, à un numéro d'onde donné, a un
#'   tracé d'IRTF et étiquetez en haut du tracé avec un texte fourni (ou par
#'   défaut le numéro d'onde du marqueur). Ceci est utile pour noter les nombres
#'   d’onde importants.
#'
#'   Cette fonction peut être appelée à plusieurs reprises. Notez que les
#'   anciennes étiquettes seront remplacées par des étiquettes plus récentes.
#'
#' @param ftir_spectra_plot A plot generated by [plot_ftir()] or
#'   [plot_ftir_stacked()].
#'
#'   Un tracé généré par [plot_ftir()] ou [plot_ftir_stacked()].
#'
#' @param wavenumber the wavenumber at which the marker should be placed.
#'
#'   le numéro d'onde auquel la compression commence
#'
#' @param text The text of the label over the marker (optional). If no text is
#'   provided, the marker will show the wavenumber (rounded to the nearest whole
#'   number).
#'
#'   Le texte de l'étiquette sur le marqueur (facultatif). Si aucun texte n'est
#'   fourni, le marqueur affichera le numéro d'onde (arrondi au nombre entier le
#'   plus proche).
#'
#' @param line_aesthetics A named `list` of aesthetics to pass to ggplot for
#'   creating the vertical line. See `[ggplot2::geom_path()]`'s aesthetics
#'   section for more info. Specifically, `alpha`, `color`, `linetype` and
#'   `linewidth` are permitted. Positioning aesthetics will be removed.
#'
#'   Une `list` nommée d'esthétiques à transmettre à ggplot pour créer la ligne
#'   verticale. Voir la section esthétique de `[ggplot2::geom_path()]` pour plus
#'   d'informations. Plus précisément, `alpha`, `color`, `linetype` et
#'   `linewidth`` sont autorisés.L’esthétique du positionnement sera supprimée.
#'
#' @param label_aesthetics A named `list` of aesthetics to pass to ggplot for
#'   creating the label. See `[ggplot2::geom_text()]`'s aesthetics section for
#'   more info. Specifically, `alpha`, `color`, `family`, `fill`, `fontface` and
#'   `size`are permitted. Positioning aesthetics will be removed.
#'
#'   Une `list` nommée d'esthétiques à transmettre à ggplot pour créer
#'   l'étiquette. Voir la section esthétique de `[ggplot2::geom_text()]` pour
#'   plus d'informations. Plus précisément, `alpha`, `color`, `family`, `fill`,
#'   `fontface` et `size` sont autorisés. L’esthétique du positionnement sera
#'   supprimée.
#'
#' @return the FTIR plot as a ggplot2 object, with a marker added at the
#'   specified wavenumber.
#'
#'   le tracé IRTF en tant qu'objet ggplot2, avec un marqueur ajouté au numéro
#'   d'onde spécifié.
#'
#' @seealso See `vignette("ggplot2-specs")` for more information on setting
#'   aesthetics.
#'
#'   Voir `vignette("ggplot2-specs")` pour plus d'informations sur la définition
#'   de l'esthétique.
#'
#' @export
#'
#' @examples
#' # Generate a plot
#' biodiesel_plot <- plot_ftir(biodiesel)
#'
#' # Add a marker at 1742 cm^-1 for the carbonyl C=O Stretch
#' p <- add_wavenumber_marker(biodiesel_plot, 1742, text = "C=O Stretch")
#' p
#'
#' # Add a second marker and use a dashed line for the C-H aliphatic stretch
#' add_wavenumber_marker(p, 2920, text = "C-H Stretch", line_aesthetics = list("linetype" = "dashed"))
add_wavenumber_marker <- function(ftir_spectra_plot, wavenumber, text = NULL, line_aesthetics = NULL, label_aesthetics = NULL) {
  if (!is.numeric(wavenumber)) {
    cli::cli_abort("{.arg wavenumber} must be a numeric value. You provided {.obj_type_friendly {wavenumber}}.")
  }

  if (!is.null(text)) {
    if (is.data.frame(text) | is.matrix(text)) {
      cli::cli_abort("{.arg text} must be character or numeric, you provided {.obj_type_friendly {text}}.")
    } else if (!is.numeric(text) & !is.character(text)) {
      cli::cli_abort("{.arg text} must be character or numeric, you provided {.obj_type_friendly {text}}.")
    } else if (length(text) > 1) {
      cli::cli_abort("{.arg text} should be character or numeric, but not a vector of length greater than one.")
    }
  } else {
    text <- as.character(as.integer(wavenumber))
  }

  if (!ggplot2::is.ggplot(ftir_spectra_plot)) {
    cli::cli_abort("{.arg ftir_spectra_plot} must be a ggplot object. You provided {.obj_type_friendly {ftir_spectra_plot}}.")
  }

  if (wavenumber < 400 || wavenumber > 4000) {
    cli::cli_abort("{.arg wavenumber} must be a value between 400 and 4000 cm^-1.")
  }

  p <- ftir_spectra_plot -
    rlang::inject(ggplot2::geom_vline(xintercept = wavenumber, !!!line_aesthetics)) +
    rlang::inject(ggplot2::annotate("label", label = text, x = wavenumber, y = Inf, vjust = 1, !!!label_aesthetics))

  return(p)
}
