#' Zoom in on a spectral range
#'
#' @description It's common to be interested in only a small portion of the FTIR
#'   range. In these cases, this function will zoom the spectral plot to the
#'   range provided.
#'
#'   Il est courant de s'intéresser uniquement à une petite partie de la plage
#'   FTIR. Dans ces cas, cette fonction zoomera sur le tracé spectral sur la
#'   plage fournie.
#'
#'
#' @param ftir_spectra_plot A plot generated by [plot_ftir()] or
#'   [plot_ftir_stacked()].
#'
#'   Un tracé généré par [plot_ftir()] ou [plot_ftir_stacked()].
#'
#' @param zoom_range A vector of length two, with the wavenumber range of
#'   interest. Order of provided limits is not important.
#'
#'   Un vecteur de longueur deux, avec la plage de nombres d'onde qui nous
#'   intéresse. L’ordre des limites fournies n’est pas important.
#'
#' @return a ggplot2 object, with x axis limits as those supplied by
#'   `zoom_range`.
#'
#'   un objet ggplot2, avec des limites d'axe x comme celles fournies par `zoom_range`.
#'
#' @export
#'
#' @examples
#' # Generate a plot
#' biodiesel_plot <- plot_ftir(biodiesel)
#'
#' # Zoom to a specified range of 1850 to 1650 cm^-1
#' zoom_in_on_range(biodiesel_plot, c(1650, 1850))
zoom_in_on_range <- function(ftir_spectra_plot, zoom_range = c(1000, 1900)) {
  if (!(inherits(ftir_spectra_plot, "ggplot"))) {
    cli::cli_abort("{.arg ftir_spectra_plot} must be a ggplot object. You provided a {.cls {class ftir_spectra_plot}}")
  }

  if (!(length(zoom_range) == 2)) {
    cli::cli_abort("{.arg zoom_range} must be a numeric vector of length two.")
  }
  if (!all(is.numeric(zoom_range))) {
    cli::cli_abort("{.arg zoom_range} must be numeric values")
  }

  if (any(zoom_range < 400) || any(zoom_range > 4000)) {
    cli::cli_abort("{.arg zoom_range} must be values between 400 and 4000 cm^-1.")
  }

  suppressMessages(p <- ftir_spectra_plot + ggplot2::scale_x_reverse(limits = c(max(zoom_range), min(zoom_range))))

  return(p)
}


#' Compression Transformation
#'
#' @description used in `compress_low_energy()`
#' utilisé en `compress_low_energy`()`
#'
#' @param intercept the wavenumber at which compression starts
#' le numéro d'onde auquel la compression commence
#' @param reducer the rate of compression (larger numbers are more compressed)
#' le taux de compression (des nombres plus grands sont plus compressés)
#'
#' @references From https://stackoverflow.com/a/43321639 & https://stackoverflow.com/a/78360580
#' @keywords internal
compress_trans <- function(intercept = 2000, ratio = 5) {
  # For FTIR, note that the plot has scale_x_reverse() always applied to it.
  # So, we're really talking about intercept as a -1*intercept

  intercept <- intercept * -1

  scales::trans_new("compress",
                    transform = function(x) {
                      ifelse(x > intercept, x, (x - intercept) / ratio + intercept)
                    },
                    inverse = function(x) {
                      ifelse(x > intercept, x, ((x - intercept) * ratio) + intercept)
                    }
  )
}



#' Compress Low-Energy Region
#'
#' @description Compress the lower energy region of a plot (on the x axis) to
#'   leave more space for the higher-energy region. This is commonly done for
#'   wavenumbers higher than 2000 cm^-1 as the more complex spectra at higher
#'   energy (lower wavenumber) is harder to see clearly.
#'
#'   Compressez la région d'énergie inférieure d'un tracé (sur l'axe des x) pour
#'   laisser plus d'espace à la région d'énergie supérieure. Ceci est
#'   généralement effectué pour les nombres d'onde supérieurs à 2000 cm^-1, car
#'   les spectres plus complexes à une énergie plus élevée (nombre d'onde
#'   inférieur) sont plus difficiles à voir clairement.
#'
#' @param ftir_spectra_plot A plot generated by [plot_ftir()] or
#'   [plot_ftir_stacked()].
#'
#'   Un tracé généré par [plot_ftir()] ou [plot_ftir_stacked()].
#'
#' @param cutoff The wavenumber whereat those at lower energy will be
#'   compressed, but those above will be shown normally.
#'
#'   Le nombre d'onde auquel ceux à énergie au-desous seront compressés, mais
#'   ceux au-dessus seront affichés normalement.
#'
#' @param compression_ratio A numeric value indicating the ratio by which to
#'   squeeze the data
#'
#'   Une valeur numérique indiquant le rapport selon lequel compresser les
#'   données
#'
#' @return a ggplot2 object, with x axis compressed for some wavenumber range
#'
#'   un objet ggplot2, avec l'axe x compressé pour une plage de nombres d'onde
#'
#' @export
#'
#' @examples
#' # Generate a plot
#' biodiesel_plot <- plot_ftir(biodiesel)
#'
#' # Compress below 2000 cm^-1 by a factor of 5
#' compress_low_energy(biodiesel_plot, cutoff = 2000, compression_ratio = 5)
compress_low_energy <- function(ftir_spectra_plot, cutoff = 2000, compression_ratio = 2) {
  if (!(inherits(ftir_spectra_plot, "ggplot"))) {
    cli::cli_abort("{.arg ftir_spectra_plot} must be a ggplot object. You provided a {.cls {class ftir_spectra_plot}}")
  }

  if (!is.numeric(cutoff)) {
    cli::cli_abort("{.arg cutoff} must be a numeric value")
  }

  if (cutoff < 400 || cutoff > 4000) {
    cli::cli_abort("{.arg cutoff} must be a value between 400 and 4000 cm^-1.")
  }

  if (!is.numeric(compression_ratio)) {
    cli::cli_abort("{.arg compression_ratio} must be a numeric value")
  }

  if (cutoff < 400 || cutoff > 4000) {
    cli::cli_alert_warning("{.arg cutoff} should be a value between 0.1 and 100.")
  }

  p <- ftir_spectra_plot +
    ggplot2::coord_trans(x = compress_trans(intercept = cutoff, ratio = compression_ratio))

  return(p)
}
