#' Convert Between Absorbance and Transmittance
#'
#' @description These functions allow for the convenient conversion between
#'   \%Transmittance and Absorbance units for the Y axis.
#'
#'   Converting between \%Transmittance and absorbance units for the Y axis is
#'   not a simple flipping of axis or inversion. Instead, the two are related by
#'   the following formulas:
#'
#' \deqn{
#'  A=-log_{10}(\tfrac{\%T}{100})
#' }
#'   and
#' \deqn{
#'  \%T=10^{-A}\cdot 100
#' }.
#'
#'   Ces fonctions permettent une conversion pratique entre les unités
#'   \%Transmittance et Absorbance pour l'axe Y. La conversion entre les unités
#'   \%Transmittance et Absorbance pour l'axe Y n'est pas un simple retournement
#'   d'axe ou une inversion. Au lieu de cela, les deux sont liés par les
#'   formules suivantes :
#'
#' \deqn{
#'  A=-log_{10}(\tfrac{\%T}{100})
#' }
#'   and
#' \deqn{
#'  \%T=10^{-A}\cdot 100
#' }
#'
#' @param ftir A data.frame of FTIR spectral data including column to be
#'   converted. Can't contain both `absorbance` and `transmittance` column as
#'   the receiving column would be overwritten
#'
#'   Un data.frame de données spectrales IRTF incluant la colonne à convertir.
#'   Ne peut pas contenir les colonnes `absorbance` et `transmittance` car la
#'   colonne de réception serait écrasée.
#'
#' @return a data.frame of FTIR spectral data with conversion between absorbance
#'   or transmittance as requested. Note the original data column is removed
#'   since FTIR spectral data frames can't be fed into plotting functions with
#'   both transmittance and absorbance data included.
#'
#'   un data.frame de données spectrales IRTF avec conversion entre l'absorbance
#'   ou la transmittance comme demandé. Notez que la colonne de données
#'   d'origine est supprimée car les trames de données spectrales IRTF ne
#'   peuvent pas être introduites dans les fonctions de tracé avec les données
#'   de transmittance et d'absorbance incluses.
#'
#' @examples
#' # Convert from absorbance to transmittance
#' sample_spectra_transmittance <- absorbance_to_transmittance(sample_spectra)
#'
#' # Convert back to absorbance
#' sample_spectra_absorbance <- transmittance_to_absorbance(sample_spectra_transmittance)
#'
#' @name conversion
NULL

#' @export
#' @rdname conversion
absorbance_to_transmittance <- function(ftir) {
  check_ftir_data(ftir, "PlotFTIR::absorbance_to_transmittance")
  if (!("absorbance" %in% colnames(ftir))) {
    cli::cli_abort("Error in {.fn PlotFTIR::absorbance_to_transmittance}. {.arg ftir} must contain a {.var absorbance} column.")
  }
  ftir$transmittance <- (10^(ftir$absorbance * -1)) * 100
  ftir$absorbance <- NULL

  ftir <- ftir[, c("wavenumber", "transmittance", "sample_id")]

  return(ftir)
}

#' @export
#' @rdname conversion
transmittance_to_absorbance <- function(ftir) {
  check_ftir_data(ftir, "PlotFTIR::transmittance_to_absorbance")
  if (!("transmittance" %in% colnames(ftir))) {
    cli::cli_abort("Error in {.fn PlotFTIR::transmittance_to_absorbance}. {.arg ftir} must contain a {.var transmittance} column.")
  }

  ftir$absorbance <- -log(ftir$transmittance / 100, base = 10)
  ftir$transmittance <- NULL

  ftir <- ftir[, c("wavenumber", "absorbance", "sample_id")]

  return(ftir)
}

#' Get Plot Sample IDs
#'
#' @description Get the sample IDs from a prepared plot. Useful if renaming in
#'   the plot legend.
#'
#'   Obtenez les ID d’échantillon à partir d’un tracé préparé. Utile si vous
#'   renommez dans la légende de le tracé
#'
#' @param ftir_spectra_plot A plot generated by [plot_ftir()] or
#'   [plot_ftir_stacked()].
#'
#'   Un tracé généré par [plot_ftir()] ou [plot_ftir_stacked()].
#'
#' @return A vector of factors corresponding to the sample IDs in the plot.
#'
#'   unvecteur de facteurs correspondant aux ID d'échantillon dans le tracé
#' @export
#'
#' @seealso [rename_plot_sample_ids()]
#' @examples
#' if (requireNamespace("ggplot2", quietly = TRUE)) {
#'   # Prepare a plot
#'   p <- plot_ftir(biodiesel)
#'
#'   # Get the Sample IDs
#'   get_plot_sample_ids <- (p)
#' }
get_plot_sample_ids <- function(ftir_spectra_plot) {
  # Package Checks
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    cli::cli_abort(c("{.pkg PlotFTIR} requires {.pkg ggplot2} package installation.",
      i = "Install {.pkg ggplot2} with {.code install.packages('ggplot2')}"
    ))
  }
  if (!ggplot2::is.ggplot(ftir_spectra_plot)) {
    cli::cli_abort("Error in {.fn PlotFTIR::get_plot_sample_ids}. {.arg ftir_spectra_plot} must be a ggplot object. You provided {.obj_type_friendly {ftir_spectra_plot}}.")
  }
  return(as.factor(unique(ftir_spectra_plot$data$sample_id)))
}

#' @title Check FTIR Data
#'
#' @description Check provided FTIR dataframe is appropriate for manipulation or plotting
#' Not typically called directly, but as a function in data integrety check process before
#' further calculation or plotting happens
#'
#' @param ftir A data.frame of FTIR spectral data including column to be
#'  converted. Can't contain both `absorbance` and `transmittance` column.
#'
#' @param fn The name of the function, used in printing error codes.
#'
#' @return invisible TRUE if ok, typically called for effect of failure.
#' @keywords internal
check_ftir_data <- function(ftir, fn) {
  if (!(is.data.frame(ftir))) {
    cli::cli_abort("Error in {.fn {fn}}. {.arg ftir} must be a data frame. You provided {.obj_type_friendly ftir}.")
  }
  if (!("sample_id" %in% colnames(ftir))) {
    cli::cli_abort(c("Error in {.fn {fn}}. {.arg ftir} is missing a column.",
      i = "It must contain a column named {.var sample_id}."
    ))
  }
  if (!("wavenumber" %in% colnames(ftir))) {
    cli::cli_abort(c("Error in {.fn {fn}}. {.arg ftir} is missing a column.",
      i = "It must contain a column named {.var wavenumber}."
    ))
  }
  if (!any(colnames(ftir) == "absorbance", colnames(ftir) == "transmittance")) {
    cli::cli_abort("Error in {.fn {fn}}. {.arg ftir} must have one of {.var absorbance} or {.var transmittance} columns.")
  }
  if ("absorbance" %in% colnames(ftir) && "transmittance" %in% colnames(ftir)) {
    cli::cli_abort("Error in {.fn {fn}}. {.arg ftir} cannot contain both {.var absorbance} and {.var transmittance} columns.")
  }
  if (any(!(colnames(ftir) %in% c("sample_id", "wavenumber", "absorbance", "transmittance")))) {
    cli::cli_abort("Error in {.fn {fn}}. {.arg ftir} may only contain columns {.var sample_id}, {.var wavenumber}, and one of {.var absorbance} or {.var transmittance}.")
  }

  invisible(TRUE)
}


#' Convert `ir` to `PlotFTIR` data format
#'
#' @description
#' convert data from the `ir` package to a structure that will work with `PlotFTIR`.
#'
#' convertir les données du paquet `ir` en une structure qui fonctionnera avec `PlotFTIR`.
#'
#' @param ir_data data of class `ir` from `ir` package
#'
#' données de la classe `ir` du paquet `ir`.
#' @param what which samples to convert to `PlotFTIR` format. Defaults to all available spectra.
#'
#' les échantillons à convertir au format `PlotFTIR`. Par défaut, tous les spectres disponibles
#'
#' @return a data.frame compatible with `PlotFTIR` functions
#'
#' un data.frame compatible avec les fonctions `PlotFTIR`.
#' @export
#'
#' @seealso [ir::ir_get_spectrum()] for information on how ir passes out data.
#'
#' @examples if (requireNamespace("ir", quietly = TRUE)) {
#'   # Convert samples 1 & 4 to PlotFTIR format
#'   ir_to_plotftir(ir::ir_sample_data, c(1, 4))
#' }
#'
ir_to_plotftir <- function(ir_data, what = NA) {
  # Package Checks
  if (!requireNamespace("ir", quietly = TRUE)) {
    cli::cli_abort(c("{.pkg PlotFTIR} requires {.pkg ir} package installation for this function.",
      i = "Install {.pkg ir} with {.code install.packages('ir')}"
    ))
  }

  # Param checks

  if (!("ir" %in% class(ir_data))) {
    cli::cli_abort("Error in {.fn PlotFTIR::ir_to_plotftir}. {.arg ir_data} must be of class {.cls ir}, produced by the {.pkg ir} package. You provided {.obj_type_friendly {ir_data}}.")
  }

  if (all(is.na(what))) {
    what <- seq_along(ir_data$spectra)
  }

  if (suppressWarnings(any(is.na(as.numeric(what))))) {
    if (all(what %in% ir_data$id_sample)) {
      what <- which(what %in% ir_data$id_sample)
    } else {
      cli::cli_abort("Error in {.fn PlotFTIR::ir_to_plotftir}. {.arg what} must contain the row numbers of sample spectra to extract, or exact names matching what is in {.code ir_data$id_sample}.")
    }
  }

  if (all(is.numeric(what))) {
    if (max(what) > nrow(ir_data) || min(what) < 1) {
      cli::cli_abort("Error in {.fn PlotFTIR::ir_to_plotftir}. {.arg what} must contain the row numbers of sample spectra to extract, or exact names matching what is in {.code ir_data$id_sample}.")
    }
  }

  # Call function
  return(ir_to_df(ir = ir_data, what = what))
}

ir_to_df <- function(ir, what) {
  # Internal function for ir_to_plotftir()
  if (!requireNamespace("ir", quietly = TRUE)) {
    cli::cli_abort(c("{.pkg PlotFTIR} requires {.pkg ir} package installation for this function.",
      i = "Install {.pkg ir} with {.code install.packages('ir')}"
    ))
  }

  # Param checks

  if (!("ir" %in% class(ir))) {
    cli::cli_abort("Error in {.fn PlotFTIR::ir_to_df}. {.arg ir} must be of class {.cls ir}, produced by the {.pkg ir} package. You provided {.obj_type_friendly {ir}}.")
  }

  irdata <- ir::ir_get_spectrum(ir, what = what)
  irdata <- mapply(cbind, irdata, "sample_id" = names(irdata), SIMPLIFY = F)
  irdata <- dplyr::bind_rows(irdata) |>
    dplyr::rename("wavenumber" = "x")

  intensity <- NA
  ftir <- data.frame()
  for (s in seq_along(unique(irdata$sample_id))) {
    id <- unique(irdata$sample_id)[s]
    sampleir <- irdata[irdata$sample_id == id, ]
    if (max(sampleir$y) < 10) {
      sample_intensity <- "absorbance"
      colnames(sampleir)[colnames(sampleir) == "y"] <- "absorbance"
    } else {
      sample_intensity <- "transmittance"
      colnames(sampleir)[colnames(sampleir) == "y"] <- "transmittance"
    }
    if (is.na(intensity)) {
      intensity <- sample_intensity
    }

    if (intensity == sample_intensity) {
      ftir <- rbind(ftir, sampleir)
    } else {
      if (intensity == "absorbance") {
        ftir <- rbind(ftir, transmittance_to_absorbance(sampleir))
      } else {
        ftir <- rbind(ftir, absorbance_to_transmittance(sampleir))
      }
    }
  }

  return(ftir)
}


#' Convert `PlotFTIR` data to `ir`
#'
#' @param ftir
#'   A data.frame in long format with columns `sample_id`,
#'   `wavenumber`, and `absorbance`. The `absorbance` column may be replaced by
#'   a `transmittance` column for transmittance plots. The code determines the
#'   correct y axis units and labels the plot/adjusts the margins appropriately.
#'
#'   Un data.frame au format long avec les colonnes `sample_id`, `wavenumber`,
#'   et `absorbance`. La colonne `absorbance` peut être remplacée par une
#'   colonne `transmittance` pour les tracés de transmission. Le code détermine
#'   les unités correctes de l'axe y et étiquette le tracé/ajuste les marges de
#'   manière appropriée.
#'
#' @param metadata
#'   Additional data to pass to `ir` to include as metadata. Should be structured
#'   as a data.frame.
#'
#'   Données supplémentaires à transmettre à `ir` pour les inclure dans les métadonnées.
#'   Doit être structuré comme un data.frame.
#'
#' @seealso [ir::ir_new_ir()] for information on how ir takes in data.
#'
#' @return
#' an `ir` classed data.frame structured for use in that package.
#'
#' un data.frame de classe `ir` structuré pour être utilisé dans ce paquet.
#' @export
#'
#' @examples
#' if (requireNamespace("ir", quietly = TRUE)) {
#'   # convert biodiesel to a `ir` object
#'   plotftir_to_ir(ir::ir_sample_data, c(1, 4))
#' }
plotftir_to_ir <- function(ftir, metadata = NA) {
  # Package checks
  if (!requireNamespace("ir", quietly = TRUE)) {
    cli::cli_abort(c("{.pkg PlotFTIR} requires {.pkg ir} package installation for this function.",
      i = "Install {.pkg ir} with {.code install.packages('ir')}"
    ))
  }

  # Param Checks
  check_ftir_data(ftir, "PlotFTIR::plotftir_to_ir")
  if (!all(is.na(metadata))) {
    if (!is.data.frame(metadata)) {
      cli::cli_abort("Error in {.fn PlotFTIR::plotftir_to_ir}. {.arg metadata} must be either {.code NA} or a {.cls data.frame}.")
    }
  }

  samples <- unique(ftir$sample_id)
  colnames(ftir)[colnames(ftir) == "wavenumber"] <- "x"
  colnames(ftir)[colnames(ftir) %in% c("transmittance", "absorbance", "intensity")] <- "y"
  ftir_ir <- lapply(samples, FUN = function(x) ftir[ftir$sample_id == x, c("x", "y"), ])
  names(ftir_ir) <- samples
  if (all(is.na(metadata)) || !is.data.frame(metadata)) {
    metadata <- data.frame("id_sample" = samples)
  } else {
    if (!("id_sample" %in% colnames(metadata))) {
      metadata$id_sample <- samples
    }
  }
  irdata <- ir::ir_new_ir(spectra = ftir_ir, metadata = metadata)

  return(irdata)
}
