#' Convert Between Absorbance and Transmittance
#'
#' @description These functions allow for the convenient conversion between \%
#'  Transmittance and Absorbance units for the Y axis.
#'
#'  Converting between %Transmittance and absorbance units for the Y axis is not
#'  a simple flipping of axis or inversion. Instead we know that the two are
#'  related by the following formulas:
#' \deqn{
#'  A=-log_{10}(\tfrac{\%T}{100})
#' }
#'  and
#' \deqn{
#'  \%T=10^{-A}\cdot 100
#' }.
#'
#'  Ces fonctions permettent une conversion pratique entre les unités \% de
#'  transmission et d'absorption pour l'axe Y.
#'
#'  La conversion entre les unités de \% de transmission et d'absorbance pour
#'  l'axe Y n'est pas un simple retournement d'axe ou une inversion. Au lieu de
#'  cela, nous savons que les deux sont liés par les formules suivantes:
#'
#' \deqn{
#'  A=-log_{10}(\tfrac{\%T}{100})
#' }
#'  and
#' \deqn{
#'  \%T=10^{-A}\cdot 100
#' }
#'
#' @param ftir A data.frame of FTIR spectral data including column to be
#'  converted. Can't contain both `absorbance` and `transmittance` column as the
#'  receiving column would be overwritten
#'
#'  Une data.frame de données spectrales IRTF comprenant la colonne à convertir.
#'  Ne peut pas contenir à la fois les colonnes `absorbance` et `transmittance`,
#'  car la colonne de réception serait écrasée.
#'
#' @return a data.frame of FTIR spectral data with conversion between absorbance
#'  and transmittance as requested. Note the original data column is removed
#'  since FTIR spectral data frames can't be fed into plotting functions with
#'  both transmittance and absorbance data included.
#'
#'  une data.frame de données spectrales IRTF avec conversion entre
#'  l'absorbance et la transmission comme demandé. Notez que la colonne de
#'  données d'origine est supprimée car les trames de données spectrales IRTF ne
#'  peuvent pas être introduites dans les fonctions de traçage avec les données
#'  de transmission et d'absorbance incluses.
#'
#' @examples
#' # Convert from absorbance to transmittance
#' sample_spectra_transmittance <- absorbance_to_transmittance(sample_spectra)
#'
#' # Convert back to absorbance
#' sample_spectra_absorbance <- transmittance_to_absorbance(sample_spectra_transmittance)
#'
#' @name conversion
NULL

#' @export
#' @rdname conversion
absorbance_to_transmittance <- function(ftir) {
  if ("absorbance" %in% colnames(ftir) && "transmittance" %in% colnames(ftir)) {
    cli::cli_abort("{.arg ftir} cannot contain both {.var absorbance} and {.var transmittance} columns.")
  }
  if (!("absorbance" %in% colnames(ftir))) {
    cli::cli_abort("{.arg ftir} must contain a {.var absorbance} column.")
  }
  ftir$transmittance <- (10^(ftir$absorbance * -1)) * 100
  ftir$absorbance <- NULL

  ftir <- ftir[, c("wavenumber", "transmittance", "sample_id")]

  return(ftir)
}

#' @export
#' @rdname conversion
transmittance_to_absorbance <- function(ftir) {
  if ("absorbance" %in% colnames(ftir) && "transmittance" %in% colnames(ftir)) {
    cli::cli_abort("{.arg ftir} cannot contain both {.var absorbance} and {.var transmittance} columns.")
  }
  if (!("transmittance" %in% colnames(ftir))) {
    cli::cli_abort("{.arg ftir} must contain a {.var transmittance} column.")
  }
  ftir$absorbance <- -log(ftir$transmittance / 100, base = 10)
  ftir$transmittance <- NULL

  ftir <- ftir[, c("wavenumber", "absorbance", "sample_id")]

  return(ftir)
}

#' Get Plot Sample IDs
#'
#' @description Get the sample IDs from a prepared plot. Useful if renaming in
#'   the plot legend.
#'
#'   Obtenez les ID d’échantillon à partir d’un tracé préparé. Utile si vous
#'   renommez dans la légende de le tracé
#'
#' @param ftir_spectra_plot A plot generated by [plot_ftir()] or
#'   [plot_ftir_stacked()].
#'
#'   Un tracé généré par [plot_ftir()] ou [plot_ftir_stacked()].
#'
#' @return A vector of factors corresponding to the sample IDs in the plot.
#'
#'   unvecteur de facteurs correspondant aux ID d'échantillon dans le tracé
#' @export
#'
#' @seealso [rename_plot_sample_ids()]
#' @examples
#' if (!requireNamespace("ggplot2", quietly = TRUE)) {
#'   # Prepare a plot
#'   p <- plot_ftir(biodiesel)
#'
#'   # Get the Sample IDs
#'   get_plot_sample_ids <- (p)
#' }
get_plot_sample_ids <- function(ftir_spectra_plot) {
  # Package Checks
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    cli::cli_abort("{.fun plot_ftir} requires {.pkg ggplot2} package installation.")
  }
  if (!ggplot2::is.ggplot(ftir_spectra_plot)) {
    cli::cli_abort("{.arg ftir_spectra_plot} must be a ggplot object. You provided {.obj_type_friendly {ftir_spectra_plot}}.")
  }
  return(as.factor(unique(ftir_spectra_plot$data$sample_id)))
}
